# Arithmatic Operators

# 1D Array

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
add_arr = arr + 3
print(add_arr)

[4 5 6 7]


In [9]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.add(arr,arr1)
print(op)
add_arr = arr + arr1
print(add_arr)

[2 4 6 8]
[2 4 6 8]


In [12]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.subtract(arr,arr1)
print(op)
add_arr = arr - arr1
print(add_arr)

[0 0 0 0]
[0 0 0 0]


In [13]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.multiply(arr,arr1)
print(op)
add_arr = arr * arr1
print(add_arr)

[ 1  4  9 16]
[ 1  4  9 16]


In [14]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.divide(arr,arr1)
print(op)
add_arr = arr / arr1
print(add_arr)

[1. 1. 1. 1.]
[1. 1. 1. 1.]


In [16]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.mod(arr,arr1)
print(op)
add_arr = arr % arr1
print(add_arr)

[0 0 0 0]
[0 0 0 0]


In [17]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.power(arr,arr1)
print(op)
add_arr = arr ** arr1
print(add_arr)

[  1   4  27 256]
[  1   4  27 256]


In [24]:
arr = np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
op = np.reciprocal(arr)
print(op)

[1 0 0 0]


# 2D Array

In [20]:
arr21 = np.array([[1,2,3,4],[1,2,3,4]])
arr22 = np.array([[1,2,3,4],[1,2,3,4]])

add = arr21 + arr22

print(add)

[[2 4 6 8]
 [2 4 6 8]]
