# Array



In [9]:
import numpy as np

x = [1,2,3,4,5]

y = np.array(x)

print(y)
print(type(y))
print(y.ndim)


[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [8]:
list = []

for i in range(1,5):
    int_1 = int(input("enter :"))
    list.append(int_1)

print(np.array(list))

enter :55
enter :58
enter :69
enter :88
[55 58 69 88]


# Two Dimensional Array (2D-Array)

In [10]:
arr2 = np.array([[1,2,3,4,5],[8,9,7,5,2]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4 5]
 [8 9 7 5 2]]
2


# Three Dimensional Array

In [12]:
arr3 = np.array([[[1,2,3,4],[8,9,7,5],[5,9,7,3]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [8 9 7 5]
  [5 9 7 3]]]
3


# N Dimensional Array

In [20]:
arrn = np.array([5,9,8,6,4,], ndmin = 6)
print(arrn)
print(arrn.ndim)

[[[[[[5 9 8 6 4]]]]]]
6
