In [3]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
print(arr1 + arr2)

[2 4 6 8]


In [14]:
arr1 = np.array([1,2,3,4])
print(arr1)
print()
print(arr1.shape)
print(np.max(arr1))
print()
arr2 = np.array([[1],[2],[3],[4]])
print(arr2)
print()
print(arr2.shape)
print(np.max(arr2))
print()
print(arr1 + arr2)

[1 2 3 4]

(4,)
4

[[1]
 [2]
 [3]
 [4]]

(4, 1)
4

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [16]:
arr1 = np.array([[1],[2]])
arr2 = np.array([[1,2,3],[1,2,3]])

print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2)

[[1]
 [2]]

[[1 2 3]
 [1 2 3]]

[[2 3 4]
 [3 4 5]]
