# Data Types

In [2]:
import numpy as np
arr = np.array([5,8,3,5])
print("Data Type : ",arr.dtype)

Data Type :  int32


In [3]:
arr = np.array([1.9,3.6])
print("Data Type :",arr.dtype)

Data Type : float64


In [5]:
arr = np.array(["S", "D","P"])
print("Data Type :", arr.dtype)

Data Type : <U1


In [6]:
arr = np.array(["S", "D","P",5,9])
print("Data Type :", arr.dtype)

Data Type : <U11


# Data Types Conversion

In [10]:
x = np.array([1,2,3,4])
print("Data Type:",x.dtype)

Data Type: int32


In [16]:
x = np.array([1,2,3,4], dtype = np.int8)
print("Data Type:",x.dtype)
print(x)

Data Type: int8
[1 2 3 4]


In [15]:
x = np.array([1,2,3,4], dtype = "f")
print("Data Type:",x.dtype)
print(x)

Data Type: float32
[1. 2. 3. 4.]


In [17]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

print("Data Type:",x2.dtype)
print("Data Type:",new.dtype)
print(x2)
print(new)

Data Type: int32
Data Type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [19]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new1 = np.int_(x2)

print("Data Type:",x2.dtype)
print("Data Type:",new.dtype)
print("Data Type:",new1.dtype)
print(x2)
print(new)
print(new1)

Data Type: int32
Data Type: float32
Data Type: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


# astype()

In [20]:
arr = np.array([1,6,8,7,6,5])
arr1 = arr.astype(float)
print(arr)
print(arr1)

[1 6 8 7 6 5]
[1. 6. 8. 7. 6. 5.]
