# Indexing

In [3]:
import numpy as np

arr1 = np.array([1,2,3,7,8,4,9])
print(arr1[2])

3


In [9]:
arr1 = np.array([1,2,3,7,5,9,3])
print(arr1[-2])

9


In [12]:
arr2 = np.array([[8,9,7,4],[4,2,6,3]])
print(arr2)
print(arr2.ndim)
print()
print(arr2[0,1])

[[8 9 7 4]
 [4 2 6 3]]
2

9


In [28]:
arr3 = np.array([[[1,2,3,4],[4,5,6,7],[9,8,7,5]]])
print(arr3)
print()
print(arr3.ndim)
print()
print(arr3[0,1,2])

[[[1 2 3 4]
  [4 5 6 7]
  [9 8 7 5]]]

3

6


# Slicing

In [37]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print()
print(arr1.ndim)
print()
print("2 to 7 =",arr1[1:7])
print("2 to End =",arr1[1:])
print("start to 6 =",arr1[:6])
print("alternate =",arr1[::2])

[1 2 3 4 5 6 7 8 9]

1

2 to 7 = [2 3 4 5 6 7]
2 to End = [2 3 4 5 6 7 8 9]
start to 6 = [1 2 3 4 5 6]
alternate = [1 3 5 7 9]


In [47]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print()
print(arr2[2,0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]


In [1]:
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print()
print(arr3[0,2:])

arr4 = np.array([[[1,2,3,4],[5,9,8,4],[4,6,7,9]]])



[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

[[7 8 9]]
