# Insert:

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print()
arr1 = np.insert(arr,5,6)
print(arr1)
print()
arr2 = np.insert(arr,(2,4),40)
print(arr2)

[1 2 3 4 5]

[1 2 3 4 5 6]

[ 1  2 40  3  4 40  5]


In [6]:
var1 = np.array([[1,2,3],[4,5,6]])
v =  np.insert(var1,2,6,axis=0)
print(v)
print()
v =  np.insert(var1,2,6,axis=1)
print(v)

[[1 2 3]
 [4 5 6]
 [6 6 6]]

[[1 2 6 3]
 [4 5 6 6]]


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
v = np.insert(arr,1,[51,31],axis=1)
print(v)
print()
v = np.insert(arr,1,[51,31,22],axis=0)
print(v)

[[ 1 51  2  3]
 [ 4 31  5  6]]

[[ 1  2  3]
 [51 31 22]
 [ 4  5  6]]


# Append:

In [12]:
arr = np.array([1,2,3,4])
ap = np.append(arr,8)
print(ap)

[1 2 3 4 8]


In [20]:
arr = np.array([[1,2,3],[4,5,6]])
app = np.append(arr,[[7,8,9]],axis=0)
print(app)
print()
# app = np.append(arr,[[7,8,9]],axis=1)
# print(app)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Delete

In [25]:
arr = np.array([1,2,3,4,5])
print(arr)
print()
d = np.delete(arr,2)
print(d)

[1 2 3 4 5]

[1 2 4 5]


In [27]:
arr = np.array([[1,2,3],[4,5,6]])
de = np.delete(arr,2)
print(de)

[1 2 4 5 6]
