# Iteration

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print()
for i in arr:
    print(i)

[1 2 3 4 5 6 7 8 9]

1
2
3
4
5
6
7
8
9


In [7]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print()
for i in arr2:
    print(i)
    
print()

for j in arr2:
    for k in j:
        print(k)
    

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [13]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

for i in arr3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
2
3
4
5
6
7
8
9


In [12]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print()
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

1
2
3
4
5
6
7
8
9


In [16]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print()
for i in np.nditer(arr3,flags=['buffered'], op_dtypes=["S"]):
    print(i)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [20]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print()
for i,d in np.ndenumerate(arr3):
    print(i,d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
