# Join Array

1.Concatenate

In [12]:
import numpy as np
# 1D array
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])

cont = np.concatenate((arr,arr1))
print(cont)

[1 2 3 4 5 6 7 8]


In [11]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[9,8,7],[6,5,4]])

print(arr)

print()

print(arr1)

print()

cont = np.concatenate((arr,arr1))

print(cont)

print()

axis0 = np.concatenate((arr,arr1),axis=0)

print(axis0)

print()

axis1 = np.concatenate((arr,arr1),axis=1)

print(axis1)

[[1 2 3]
 [4 5 6]]

[[9 8 7]
 [6 5 4]]

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 5 4]]

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 5 4]]

[[1 2 3 9 8 7]
 [4 5 6 6 5 4]]


# stack

In [17]:
arr = np.array([1,2,3,4])
arr1 = np.array([5,6,7,8])
# stack
stack = np.stack((arr,arr1),axis=1)
print(stack)
print()

# hstack toward Row
hstack = np.hstack((arr,arr1))
print(hstack)
print()

# vstack towards Column
vstack = np.vstack((arr,arr1))
print(vstack)
print()

# dstack toward height
dstack = np.dstack((arr,arr1))
print(dstack)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Split Array

In [28]:
# 1D Array.
arr = np.array([1,2,3,4])
print(arr)
print()

split = np.array_split(arr,4)
print(split)
print(split[1])

[1 2 3 4]

[array([1]), array([2]), array([3]), array([4])]
[2]


In [34]:
#2D Array.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()

split = np.array_split(arr,3)
print(split)
print()

split0 = np.array_split(arr,3,axis=0)
print(split0)
print()

split1 = np.array_split(arr,3,axis=1)
print(split1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
