# Transpose:

In [1]:
import numpy as np
mat = np.matrix([[1,2,3],[4,5,6]])
print(mat)
print()
print(np.transpose(mat))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes: convert column to row and vise versa

In [5]:
mat = np.matrix([[1,2,3],[4,5,6]])
print(np.swapaxes(mat,0,1))
print()
mat2 = np.matrix([[1,2],[3,4]])
print(mat2)
print()
print(np.swapaxes(mat2,0,1))

[[1 4]
 [2 5]
 [3 6]]

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# Inverse: A^-1

In [6]:
mat = np.matrix([[1,2],[3,4]])
print(mat)
print()
print(np.linalg.inv(mat))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power:

In [8]:
mat = np.matrix([[1,2],[3,4]])
print(mat)
print()
print(np.linalg.matrix_power(mat,2))
print()
print(np.linalg.matrix_power(mat,0))
print()
print(np.linalg.matrix_power(mat,-2))
print()


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



# Determinant:

In [9]:
mat = np.matrix([[1,2],[3,4]])
print(mat)
print()
print(np.linalg.det(mat))

[[1 2]
 [3 4]]

-2.0000000000000004
