# Matrix:

In [7]:
import numpy as np
arr = np.matrix([[1,2,3],[4,5,6]])
arr1 = np.matrix([[1,2,3],[4,5,6]])
print(type(arr))
print(arr.ndim)
print(arr)
print()
print(arr1)
print()
print(arr + arr1)

<class 'numpy.matrix'>
2
[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]


In [12]:
arr = np.array([[1,2],[4,5]])
arr = np.array([[1,2],[4,5]])
print(arr*arr1)
print()
print(arr.dot(arr1))

[[ 9 12 15]
 [24 33 42]]

[[ 9 12 15]
 [24 33 42]]
