# Random

# 1.Rand() for only number from 0 to 1

In [3]:
import numpy as np
arr_rand = np.random.rand(3)
print(arr_rand)

[0.83576982 0.0826156  0.58809773]


In [4]:
arr_2d = np.random.rand(2,6)
print(arr_2d)

[[0.01989613 0.75518128 0.93863536 0.67312804 0.23787979 0.66536888]
 [0.10796054 0.88805586 0.97225385 0.39255402 0.41218584 0.12079172]]


In [6]:
arr_3d = np.random.rand(6,3)
print(arr_3d)

[[0.1999776  0.30403954 0.22397849]
 [0.12073459 0.30141228 0.77180859]
 [0.96589349 0.18325365 0.69368387]
 [0.75365675 0.9872264  0.64419545]
 [0.51848166 0.18073289 0.53424416]
 [0.95611456 0.14883644 0.27307679]]


# Randn() for negative as well positive numbers

In [7]:
arr_randn = np.random.randn(5)
print(arr_randn)

[-0.75742961  0.28845177 -0.17390183  0.87691979  0.57925779]


# Ranf num form [0.0 to 1.0]

In [8]:
arr_ranf = np.random.ranf(6)
print(arr_ranf)

[0.12608712 0.3986702  0.72001151 0.99020489 0.67829661 0.32870288]


# Randint it give num from given range of num (4,9)

In [13]:
arr_randint = np.random.randint(4,50,7)
print(arr_randint)

[31 34  6 43 25 20 46]
