# Search, Sorted, Search_sorted, Filter.

# Search:

In [6]:
import numpy as np
arr= np.array([1,2,3,4,6,7,8,9,2,4,6,8,5,7,6,5,6,1,2,3,4])

s = np.where(arr == 4)
print(s)
print()

d = np.where((arr%2) == 0)
print(d)
print()

a = np.where((arr + 2) == 6)
print(a)

(array([ 3,  9, 20], dtype=int64),)

(array([ 1,  3,  4,  6,  8,  9, 10, 11, 14, 16, 18, 20], dtype=int64),)

(array([ 3,  9, 20], dtype=int64),)


# SearchSorted:

In [15]:
arr = np.array([1,3,5,6,7,9,])
ss = np.searchsorted(arr, 4)
print(ss)

2


In [16]:
arr = np.array([1,2,3,5,6,8,4,9,8])
ri = np.searchsorted(arr,4,side="right")
print(ri)

3


In [17]:
arr = np.array([1,2,4,5,7,8])
li = np.searchsorted(arr,[3,6,9])
print(li)

[2 4 6]


# Sort:

In [18]:
# 1D array
arr = np.array([1,5,69,4,65,7,9,3,8,77,22,5,33])
sort = np.sort(arr)
print(sort)

[ 1  3  4  5  5  7  8  9 22 33 65 69 77]


In [19]:
arr = np.array(["a","z","b","x","p"])
sort = np.sort(arr)
print(sort)


['a' 'b' 'p' 'x' 'z']


In [21]:
# 2D array
arr = np.array([[11,2,3],[40,15,6],[71,18,9]])
sort = np.sort(arr)
print(sort)

[[ 2  3 11]
 [ 6 15 40]
 [ 9 18 71]]


# Filter:

In [23]:
arr = np.array([66,88,22,51,55])
fil = [False,True,False,True,True]

fil_array = arr[fil]
print(fil_array)

[88 51 55]
