# Shape & Reshape

# 1.Shape

In [4]:
import numpy as np
arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr)
print()
print(arr.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [5]:
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[1 2 3 4]]]]]
5
(1, 1, 1, 1, 4)


# 2.Reshape

In [17]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)
print()
x = arr.reshape(3,2)
print(x)
print(arr.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
1


In [22]:
arr = np.array([1,2,3,4,5,6,5,9,4,2,4,7])
print(arr)
print(arr.ndim)
print()
x = arr.reshape(2,3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6 5 9 4 2 4 7]
1

[[[1 2]
  [3 4]
  [5 6]]

 [[5 9]
  [4 2]
  [4 7]]]
3


In [26]:
arr = np.array([1,2,3,4,5,6,5,9,4,2,4,7,1,2,3,1,2,3])
print(arr)
print(arr.ndim)
print()
x = arr.reshape(2,3,3)
print(x)
print(x.ndim)
one = x.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 5 9 4 2 4 7 1 2 3 1 2 3]
1

[[[1 2 3]
  [4 5 6]
  [5 9 4]]

 [[2 4 7]
  [1 2 3]
  [1 2 3]]]
3
[1 2 3 4 5 6 5 9 4 2 4 7 1 2 3 1 2 3]
1
