# Shuffle

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[3 1 4 5 6 2]


# Unique:

In [13]:
arr = np.array([1,5,6,4,1,2,5,4,6,2,1,3,4,5,6])
uni = np.unique(arr, return_index=True, return_counts=True)
print(uni)

(array([1, 2, 3, 4, 5, 6]), array([ 0,  5, 11,  3,  1,  2], dtype=int64), array([3, 2, 1, 3, 3, 3], dtype=int64))


# Resize:

In [13]:
arr = np.array([1,2,3,4,5,6])
size = np.resize(arr,(2,3))
print(size)
print()
size = np.resize(arr,(2,3,1))
print(size)

[[1 2 3]
 [4 5 6]]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


# Flatten:

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
flat = arr.flatten()

print(flat)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [33]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print()
flat = arr.flatten(order="C")
print(flat)
print()
flat = arr.flatten(order="F")
print(flat)
print()
flat = arr.flatten(order="A")
print(flat)
print()
flat = arr.flatten(order="K")
print(flat)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[1 4 2 5 3 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]


# Revel:

In [ ]:
arr = np.array([[[1,2,3,4,5,6,7,8,9]]])
rav = np.ravel(arr)
print(rav)

[1 2 3 4 5 6 7 8 9 4]


In [40]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
print(arr)
print()
rav = np.ravel(arr, order="K")
print(rav)

[[1 2 3 4 5 6 7 8 9]]

[1 2 3 4 5 6 7 8 9]
