# Zeros Array

In [2]:
import numpy as np
arr_zero = np.zeros(4)
print(arr_zero)
print()
arr_zero1 = np.zeros((4,4))
print(arr_zero1)
print()
arr_zero1 = np.zeros((4,4,4))
print(arr_zero1)



[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# Ones Filled Array

In [14]:
arr_ones = np.ones(4)
print(arr_ones)
print()
arr_one1 = np.ones(((5,5)))
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Empty Array

In [15]:
arr_emp = np.empty(4)
print(arr_emp)

[1. 1. 1. 1.]


# Arange Array

In [16]:
arr_range = np.arange(4)
print(arr_range)

[0 1 2 3]


# Digonal One (Eye())

In [17]:
arr_dg = np.eye(3)
print(arr_dg)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
arr_dg = np.eye(6,6)
print(arr_dg)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Linspace Array

In [22]:
arr_lin = np.linspace(0,100,num=5)
print(arr_lin)

[  0.  25.  50.  75. 100.]
